# Generated by Django 2.1.7 on 2019-04-23 17:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('niv', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asesor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_adviser', models.CharField(blank=True, max_length=3, verbose_name='ID Asesor')),
                ('nombre', models.CharField(max_length=30, verbose_name='Nombre')),
            ],
        ),
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Fecha')),
                ('time', models.TimeField(verbose_name='Hora')),
                ('seen', models.BooleanField(default=False, verbose_name='Visto')),
                ('adviser', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='taller.Asesor')),
                ('niv', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='niv.Niv')),
            ],
        ),
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job', models.CharField(blank=True, max_length=6, verbose_name='Jobs')),
                ('date', models.CharField(blank=True, max_length=8, verbose_name='Fecha de recepcion')),
                ('description', models.CharField(blank=True, max_length=40, verbose_name='Descripcion')),
                ('niv', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='niv.Niv')),
            ],
        ),
        migrations.CreateModel(
            name='PreCita',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(verbose_name='Fecha Creada')),
                ('preferred_date', models.DateField(verbose_name='Fecha Preferida')),
                ('preferred_time', models.CharField(max_length=10, verbose_name='Horario Preferido')),
                ('mileage', models.CharField(max_length=9, verbose_name='Kilometraje')),
                ('niv', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='niv.Niv')),
            ],
        ),
    ]
