# Generated by Django 2.1.7 on 2019-04-23 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taller', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='precita',
            name='created',
            field=models.DateField(verbose_name='Fecha Creada'),
        ),
    ]
